1. Create a numpy array of size 10, filled with zeros

In [1]:
import numpy as np

zeros_array = np.zeros(10)
print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Create a numpy array with values ranging from 10 to 49

In [54]:
#once import numpy is defined as np, we dont need to define it again
array_10_to_49 = np.arange(10, 50)
print(array_10_to_49)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a numpy matrix of 2*2 integers, filled with ones

In [55]:
ones_matrix = np.ones((2, 2), dtype=int)
print(ones_matrix)


[[1 1]
 [1 1]]


4. Create a numpy matrix of 3*2 float numbers, filled with ones

In [4]:
ones_float_matrix = np.ones((3, 2), dtype=float)
print(ones_float_matrix)



[[1. 1.]
 [1. 1.]
 [1. 1.]]


5. Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [35]:
X = np.array([[1, 2, 3],[4, 5, 6]]) #array X is defined
ones = np.ones_like(X) #array called ones with the same shape and type as X filled with ones is made using X array
print(ones)


[[1 1 1]
 [1 1 1]]


6. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [37]:
X = np.array([[1, 2], [3, 4]]) #array X is defined
zeros = np.zeros_like(X) #matrix called ones with the same shape and type as X filled with zeros is made
print(zeros)



[[0 0]
 [0 0]]


7. Create a numpy matrix of 4*4 integers, filled with fives

In [38]:
fives = np.full((4, 4), 5, dtype=int) #a 4x4 matrix filled with fives defined
print(fives)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


8. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [9]:
X = np.array([[1, 2], [3, 4]]) #array X is defined
sevens = np.full_like(X, 7) #a matrix called with the same shape and type as X filled with sevens is made
print(sevens)


[[7 7]
 [7 7]]


9. Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [10]:
identity_matrix = np.eye(3) #a 3x3 identity matrix is made
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


10. Create a numpy array, filled with 3 random integer values between 1 and 10

In [39]:
random = np.random.randint(1, 11, size=3)#a NumPy array called random with 3 random integers between 1 and 10 is defined
print(random)


[5 4 5]


11. Create a 3*3*3 numpy matrix, filled with random float values.

In [40]:
random = np.random.rand(3, 3, 3) #a 3x3x3 matrix called random filled with random float values is made
print(random)


[[[0.39159406 0.41985724 0.81409892]
  [0.51584913 0.88724286 0.35758392]
  [0.7880818  0.44238044 0.41308358]]

 [[0.32721917 0.4161508  0.05109807]
  [0.2881235  0.57330325 0.92759186]
  [0.0412704  0.88014145 0.32623259]]

 [[0.23645305 0.53877026 0.93506525]
  [0.32695181 0.60249266 0.42120691]
  [0.57747802 0.84351698 0.74720144]]]


12. Create a numpy array with numbers from 1 to 10

In [41]:
array = np.arange(1, 11) #a NumPy array called array with numbers from 1 to 10 is defined
print(array)


[ 1  2  3  4  5  6  7  8  9 10]


13. Create a numpy array with the odd numbers between 1 to 10

In [42]:
odd= np.arange(1, 11, 2) #a NumPy array called odd with odd numbers from 1 to 10 is defined
print(odd)


[1 3 5 7 9]


14. Create a numpy array with numbers from 1 to 10, in descending order.

In [43]:
desc_array = np.arange(10, 0, -1) #a NumPy array with numbers from 1 to 10 in descending order is defined
print(desc_array)


[10  9  8  7  6  5  4  3  2  1]


15. Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [16]:
matrix_3x3 = np.arange(9).reshape(3, 3) #a 3x3 numpy matrix with values ranging from 0 to 8 is made
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Array indexation
1. Given the X numpy array, show it's first element

In [45]:
X = np.array([1, 2, 3, 4, 5]) #defining X as a numpy array
first = X[0] #displaying the first element of the array
print(first)


1


2. Given the X numpy array, show it's last element

In [47]:
X = np.array([1, 2, 3, 4, 5]) #defining X as a numpy array
last = X[-1] #displaying the last element of the array
print(last)


5


3. Given the X numpy array, show it's first three elements

In [49]:
X = np.array([1, 2, 3, 4, 5]) #defining X as a numpy array
three = X[:3] #displaying the first three elements of the array
print(three)


[1 2 3]


4. Given the X numpy array, show all middle elements

In [50]:
X = np.array([1, 2, 3, 4, 5]) #defining X as a numpy array
middle= X[1:-1] #displaying all middle elements of the array
print(middle)


[2 3 4]


5. Given the X numpy array, show the elements in reverse position.

In [51]:
X = np.array([1, 2, 3, 4, 5]) #defining X as a numpy array
reverse = X[::-1] #displaying the elements in reverse position
print(reverse)


[5 4 3 2 1]


6. Given the X numpy array, show the elements in an odd position.

In [52]:
X = np.array([1, 2, 3, 4, 5]) #defining X as a numpy array
odd = X[1::2] #displaying the elements in odd positions
print(odd)


[2 4]


7. Given the X numpy matrix, show the first row elements.

In [56]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
first_row_elements = X[0] #displaying the first row elements
print(first_row_elements)


[1 2 3]


8. Given the X numpy matrix, show the last row elements.

In [24]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
last_row_elements = X[-1] #displaying the last row elements
print(last_row_elements)


[7 8 9]


9. Given the X numpy matrix, show the first element on first row

In [57]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
first= X[0, 0] #displaying the first element on the first row
print(first)


1


10. Given the X numpy matrix, show the last element on last row.

In [58]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
last = X[-1, -1] #display the last element on the last row
print(last)


9


11. Given the X numpy matrix, show the first two elements on the first two rows.

In [59]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
first_two = X[:2, :2] #displaying the first two elements on the first two rows
print(first_two)


[[1 2]
 [4 5]]


12. Given the X numpy matrix, show the last two elements on the last two rows

In [60]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
last_two = X[-2:, -2:] #displaying the last two elements on the last two rows
print(last_two)


[[5 6]
 [8 9]]


Array manipulation
1. Convert the given integer numpy array to float

In [65]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
float_array = X.astype(float) #converting the integer array to float
print(float_array)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


2. Reverse the given numpy array (first element becomes last)

In [66]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
reverse = X[::-1] #reversing the numpy array
print(reverse)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


3. Given the X numpy array, set the fifth element equal to 1

In [67]:
X = np.array([0, 0, 0, 0, 0, 0, 0]) #assuming X is your numpy array
X[4] = 1 #setting the fifth element to 1
print(X)


[0 0 0 0 1 0 0]


4. Given the X numpy matrix, change the last row with all 1

In [68]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
X[-1] = 1 #changing the last row to all ones
print(X)


[[1 2 3]
 [4 5 6]
 [1 1 1]]


5. Given the X numpy matrix, add 5 to every element

In [69]:
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #defining X as a numpy array
X = X + 5 #adding 5 to every element
print(X)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
